name: Release via Merge Queue

on:
  merge_group:

permissions:
  contents: write
  pull-requests: write


jobs:
  generate-release:
    if: github.event_name == 'merge_group'
    name: Build Release on Merge Queue
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with SSH deploy key
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install git-cliff
        uses: kenji-miyake/setup-git-cliff@v1

      - name: Get bumped version
        id: bump
        run: |
          VERSION=$(git cliff --config=cliff.toml --bumped-version)
          echo "new_tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate CHANGELOG.md
        run: |
          git cliff --config=cliff.toml --tag ${{ steps.bump.outputs.new_tag }} > CHANGELOG.md

      - name: Commit and push changelog
        run: |
          git add CHANGELOG.md
          git commit -m "skip ci: update changelog for ${{ steps.bump.outputs.new_tag }}"
          git push origin main

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.bump.outputs.new_tag }} \
            --title "Release ${{ steps.bump.outputs.new_tag }}" \
            --notes-file CHANGELOG.md \
            --repo ${{ github.repository }}
