name: Generate Changelog and Release Version on Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v1

      - name: Bump release version
        id: new_tag
        run: |
          VERSION=$(git cliff --config=cliff.toml --bumped-version)
          echo "new_tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate changelog for this version
        run: |
          git cliff --config=cliff.toml --tag ${{ steps.new_tag.outputs.new_tag }} > CHANGELOG.md

      - name: Commit and push changelog
        run: |
          git checkout ${{ steps.detect_branch.outputs.default_branch }}
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "Update changelog"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.detect_branch.outputs.default_branch }}
          
      - name: Create GitHub Release with changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.new_tag.outputs.new_tag }} \
            --title "Release ${{ steps.new_tag.outputs.new_tag }}" \
            --notes-file CHANGELOG.md \
            --repo ${{ github.repository }}

