name: Generate Changelog and Release Version on Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  changelog:
    name: Generate changelog and release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Set up git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v1

      - name: Bump release version
        id: new_tag
        run: |
          VERSION=$(git cliff --config=cliff.toml --bumped-version)
          echo "new_tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate changelog
        run: |
          git cliff --config=cliff.toml --tag ${{ steps.new_tag.outputs.new_tag }} > CHANGELOG.md

      - name: Commit and push changelog
        run: |
          git add CHANGELOG.md
          git commit -m "Update changelog for release ${{ steps.new_tag.outputs.new_tag }}"
          git push origin main

      - name: Create GitHub Release with changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.new_tag.outputs.new_tag }} \
            --title "Release ${{ steps.new_tag.outputs.new_tag }}" \
            --notes-file CHANGELOG.md \
            --repo ${{ github.repository }}

