on:
  workflow_run:
    workflows: ["Generate Changelog"]
    types:
      - completed

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Detect default branch
        id: detect_branch
        run: |
          DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d ':' -f2 | tr -d ' ')
          echo "default_branch=$DEFAULT_BRANCH" >> $GITHUB_OUTPUT


      - name: Bump new release with git-cliff
        uses: orhun/git-cliff-action@v4
        id: new_tag
        with:
          config: cliff.toml
          args: --bumped-version
        env:
          OUTPUT: NEW_TAG
          GITHUB_REPO: ${{ github.repository }}

      - name: Create GitHub Release with generated notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.new_tag.outputs.NEW_TAG }} \
            --generate-notes \
            --title "Release ${{ steps.new_tag.outputs.NEW_TAG }}" \
            --repo ${{ github.repository }}

