name: Release on Tag Push

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  changelog:
    name: Generate changelog with git-cliff and release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for full git log

      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Detect default branch and switch to it
        run: |
          DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d ':' -f2 | tr -d ' ')
          echo "DEFAULT_BRANCH=$DEFAULT_BRANCH" >> $GITHUB_ENV
          git fetch origin $DEFAULT_BRANCH
          git switch $DEFAULT_BRANCH
          git reset --hard origin/$DEFAULT_BRANCH

      - name: Generate changelog using git-cliff
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --tag ${{ env.TAG_NAME }} --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit and push updated CHANGELOG.md
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add CHANGELOG.md
          git commit -m "docs: update changelog for $TAG_NAME [auto]"
          git push origin HEAD

      - name: Create GitHub Release with changelog notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $TAG_NAME \
            --notes-file CHANGELOG.md \
            --title "Release $TAG_NAME" \
            --repo ${{ github.repository }}
