name: Create Release

on:
  workflow_run:
    workflows: ["Generate Changelog on Merge"]
    types:
      - completed

permissions:
  contents: write

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v1

      - name: Detect default branch
        id: detect_branch
        run: |
          DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d ':' -f2 | tr -d ' ')
          echo "default_branch=$DEFAULT_BRANCH" >> $GITHUB_OUTPUT

      - name: Bump release version
        id: new_tag
        run: |
          VERSION=$(git cliff --config=cliff.toml --bumped-version)
          echo "new_tag=$VERSION" >> $GITHUB_OUTPUT


      - name: Create GitHub Release with generated notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.new_tag.outputs.new_tag }} \
            --generate-notes \
            --title "Release ${{ steps.new_tag.outputs.new_tag }}" \
            --repo ${{ github.repository }}

